/FR_ROS_API_node:
	ros__parameters:
	AO_block: 1 # Whether analog output is blocked (0 - blocked, 1 - non-blocked)
	DO_block: 1 # Whether digital output is blocked (0 - blocked, 1 - non-blocked)
	DO_smooth: 0 # Digital output smoothing (0 - non-smooth, 1 - smooth)
	JOG_acc: 40 # JOG command acceleration percentage
	JOG_maxdis: 5 # Maximum angle or distance for a single JOG command, in degrees or mm
	MoveC_blendR: 500.0 # Smoothing radius for MOVEC commands. [-1.0] - Move to position (blocked), [0-1000.0] - Smoothing radius (non-blocked), in mm
	MoveJLC_acc: 0.0 # Acceleration percentage parameter for MOVEC commands (not available yet)
	MoveJLC_eaxis1: 0.0 # MOVEC commands (not available yet) Extended axis 1 position parameters
	MoveJLC_eaxis2: 0.0 #MOVEJ MOVEL MOVEC command Extended axis 2 position parameters
	MoveJLC_eaxis3: 0.0 #MOVEJ MOVEL MOVEC command Extended axis 3 position parameters
	MoveJLC_eaxis4: 0.0 #MOVEJ MOVEL MOVEC command Extended axis 4 position parameters
	MoveJLC_offset_flag: 0 #MOVEJ MOVEL MOVEC command Path offset parameter. 0 - No offset, 1 - Offset in the base coordinate system/workpiece coordinate system, 2 - Offset in the tool coordinate system
	MoveJLC_offset_pos_rx: 0.0 #MOVEJ MOVEL MOVEC command Path offset parameter - rx angle offset value
	MoveJLC_offset_pos_ry: 0.0 #MOVEJ MOVEL MOVEC command Path offset parameter - ry angle offset value
	MoveJLC_offset_pos_rz: 0.0 #MOVEJ MOVEL MOVEC command trajectory offset parameter: rz angle offset value
	MoveJLC_offset_pos_x: 0.0 #MOVEJ MOVEL MOVEC command trajectory offset parameter: x offset value
	MoveJLC_offset_pos_y: 0.0 #MOVEJ MOVEL MOVEC command trajectory offset parameter: y offset value
	MoveJLC_offset_pos_z: 0.0 #MOVEJ MOVEL MOVEC command trajectory offset parameter: z offset value
	MoveJLC_ovl: 100.0 #MOVEJ MOVEL MOVEC command velocity scaling factor parameter, range 0-100
	MoveJLC_tool: 0 #MOVEJ MOVEL MOVEC command: tool coordinate system label
	MoveJLC_user: 0 #MOVEJ MOVEL MOVEC command: workpiece coordinate system label
	MoveJ_blendT: 500.0 #MOVEJ command: smoothing time parameter [-1.0] - Move to position (blocked), [0-500.0] - Smoothing time (non-blocked), unit: ms
	MoveL_blendR: 500.0 #MOVEL command, smoothing time parameter [-1.0] - Move to position (blocked), [0-1000.0] - Smoothing radius (non-blocked), unit: mm
	MoveL_search: 0.0 #MOVEL command, wire search parameter: 0 - no wire search, 1 - wire search
	NewSpline_blendR: 10.0 #Cartesian spline command, smoothing radius parameter, unit: mm
	Spline_acc: 0.0 #Joint space spline command, acceleration percentage
	Spline_ovl: 100.0 #Joint space spline command, velocity scaling factor, range: 0-100
	Spline_tool: 1 #Joint space spline command, tool coordinate number
	Spline_user: 0 #Joint space spline command, workpiece coordinate number
	collision_config: 1 #Collision profile settings, 0 - Update profile, 1 - Do not update profile
	collision_mode: 0 #Collision level mode, 0 - level, 1 - percentage, range 0-1
	gripper_block: 1 #Blocking configuration parameter in the movegripper command, 0 - blocking, 1 - non-blocking
	gripper_force: 50 #Torque percentage configuration parameter in the movegripper command, range 0-100
	gripper_vel: 50 #Velocity percentage configuration parameter in the movegripper command, range 0-100
	gripper_maxtime: 30000 #Maximum wait time configuration parameter in the movegripper command, range 0-30000, unit ms
	qos_overrides:
		/parameter_events:
			publisher:
				depth: 1000
				durability: volatile
				history: keep_last
				reliability: reliable
	toolcoord_install: 0 #Tool installation location parameter in the SetToolCoord SetToolList command, 0 - end of robot, 1 - outside of robot
	toolcoord_type: 0 #SetToolCoord SetToolList command coordinate system type parameter. 0 - tool coordinate system, 1 - sensor coordinate system.
	ServoJT_timeinterval: 0.008 #ServoJT command cycle parameter. Default: 8ms.
	use_sim_time: false
